export const URLS = {
  JOBS: "/v1/job",
  HOLIDAYS: "/v1/holidays",
  SHIFTS: "/v1/shift",
  RATESHIFT: "/v1/rateShift",
  EMPLOYEE: "/v1/user",
  ADD_EMPLOYEE: "/v1/user/insertEmployee",
  DASHBOARD: "/v1/dashboard",
  FORGOT_PASSWORD: "/v1/auth/forgotPassword",
  VERIFY_OTP: "/v1/auth/verifyOTP",
  RESET_PASSWORD: "/v1/auth/resetPassword",
  ASSIGN_EMPLOYEE: "v1/scheduleShift/inviteEmployee",
  GET_EMPLOYEE_ATTENDANCE: "v1/attendance/getEmployee",
  ADD_MANUAL_ATTENDANCE: "v1/attendance/manualAttendance",
  GET_ATTENDANCE_DETAILS: "v1/attendance",
  PAYABLE_LIST: "v1/payment",
  SCHEDULE_SHIFT: "v1/scheduleShift",
  GET_EMPLOYEE_BY_DATE: "v1/scheduleShift/getEmployeeForAssignManualShift",
  SCHEDULE_CALENDAR: "v1/scheduleShift/getScheduleCalendar",
  REFRESH_CALENDAR: "v1/scheduleShift/refreshScheduleCalendar",
  REPEAT_SCHEDULE: "v1/scheduleShift/nextWeekOrMonth",
  PROFILE: "v1/user",
  USER_PROFILE: "v1/user/getEmployer",
  USER_PROFILE_UPDATE: "v1/user/updateEmployer",
  NOTIFICATION: "v1/notification",
  ALL_NOTIFICATION: "v1/notification/getAllNotification",
  CLEAR_NOTIFICATION: "v1/notification/seenNotification",
  SEE_NOTIFICATION: "v1/notification/seenNotificationById",
  NOTIFICATION_COUNT: "v1/notification/notificationCount",
  HOLIDAY_SETTING: "v1/setting/",
  DATE_BASED_EMPLOYEES: "v1/scheduleShift/getEmployeeForAssignManualShift",
  CHANGE_PASSWORD: "v1/auth/changePassword",
  LOGOUT: "v1/auth/logout",
};

export const pageMode = {
  ADD: "add",
  EDIT: "edit",
  VIEW: "view",
};
